version: '3.1'
services:
  app:
    image: restmongoapp
    container_name: restexample
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"