version: '3.1'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    container_name: restexample
    restart: on-failure
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongo
    restart: on-failure
    ports:
      - "27017:27017"